# Site settings
title: ThinkingDots
tag_text: thinking dots
description: visual rumination
url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]

permalink: pretty